name: Deploy to DigitalOcean registry

on:
  push:
    branches:
      - main

jobs:
  build-push-do:
    name: Docker build and Push to Digital Ocean
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DigitalOcean registry
        run: docker login registry.digitalocean.com -u dop_v1_16a56866661c0ee9736307fbfdd18fd8f2979be5ca7fad7878e99d06edcf5e5d -p dop_v1_16a56866661c0ee9736307fbfdd18fd8f2979be5ca7fad7878e99d06edcf5e5d

      - name: Build Docker image
        run: docker build -t registry.digitalocean.com/registrydo/node-web-app-test:$GITHUB_SHA .

      - name: Push Docker image to DigitalOcean registry
        run: docker push registry.digitalocean.com/registrydo/node-web-app-test:$GITHUB_SHA
